[deps]
BiGSTARS = "55e6fa54-20b2-4a8e-ba84-e72db1c430e6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[compat]
Documenter = "1"
DocumenterCitations = "1.2"
Literate = "â‰¥2.9.0"
